// Academic content. Run `node build.mjs` after editing to regenerate all pages.
export const profile = {
  name: "Xinrui Wu",
  chineseName: "吴欣锐",
  role: "Undergraduate Researcher",
  affiliation: "UESTC · Visiting Student at MBZUAI · Research Intern at Tsinghua AIR",
  educationSummary: "B.S. in Software Engineering (Embedded System), UESTC",
  email: "xinruiwu.wxr@gmail.com",
  opportunities: "I am currently seeking PhD positions for Fall 2027 and am open to job opportunities.",
  scholarUrl: "https://scholar.google.com/citations?user=pJzltu8AAAAJ&hl=en",
  alphaXivUrl: "https://www.alphaxiv.org/@xinrui-wu",
  githubUrl: "https://github.com/gintmr",
  cvUrl: "/cv/",
  cvPdfUrl: "/assets/cv/Xinrui-Wu-CV.pdf",
  portrait: "/assets/portraits/xinrui-wu-enhanced.png",
  logo: "/assets/branding/xinrui-wu-illustrated-avatar.png",
  intro: [
    "I am an undergraduate student in Software Engineering at the University of Electronic Science and Technology of China (UESTC). I am also a visiting student at MBZUAI, advised by Prof. Yutong Xie, and a research intern at the Institute for AI Industry Research (AIR), Tsinghua University, advised by Prof. Yuanchun Li.",
    "My research centers on clinical AI and world models, efficient language-model reasoning, and visual intelligence. I study how models reason over patient trajectories, control their reasoning budgets, and represent visual and temporal information.",
  ],
};

export const researchAreas = [
  {
    id: "clinical",
    title: "Clinical AI",
    description: "Clinical reasoning, longitudinal prognosis, relational trajectory modeling.",
    keywords: ["Clinical reasoning", "Relational trajectories", "Action-aware world models"],
  },
  {
    id: "reasoning",
    title: "Efficient Reasoning & Perception",
    description: "Budget-aware LLM reasoning, lightweight segmentation, distillation.",
    keywords: ["Reasoning budgets", "Controllable generation", "Test-time compute"],
  },
  {
    id: "vision",
    title: "World Models",
    description: "Visual world modeling, spatiotemporal consistency, causal reasoning.",
    keywords: ["Perception & distillation", "Spatial intelligence", "Generative modeling"],
  },
  {
    id: "spatial",
    title: "Spatial Intelligence",
    description: "3D perception, vision-language spatial reasoning, AR/VR.",
  },
  {
    id: "generative",
    title: "Generative Models",
    description: "Controllable image generation, reference-guided editing, generative model evaluation.",
  },
];

export const publications = [
  {
    id: "budgetthinker",
    shortName: "BudgetThinker",
    title: "BudgetThinker: Empowering Budget-aware LLM Reasoning with Control Tokens",
    authors: "Hao Wen*, Xinrui Wu*, Yi Sun, Feifei Zhang, Liye Chen, Jie Wang, Yifan Su, Yunxin Liu, Ya-Qin Zhang, Yuanchun Li",
    venue: "EMNLP 2026",
    year: 2026,
    status: "accepted",
    role: "first",
    roleLabel: "Co-first author",
    topic: "reasoning",
    summary: "Uses proportional control tokens and a two-stage training pipeline to align reasoning length with a specified token budget.",
    links: [{ label: "arXiv", url: "https://arxiv.org/abs/2508.17196" }],
  },
  {
    id: "maskguide",
    shortName: "MaskGuide",
    title: "MaskGuide: Efficient Distillation for Deployable Lightweight Segmentation in Marine Environments",
    authors: "Xinrui Wu*, Ziqiang Zheng*, Yiwei Chen, Zeyu Ma+, Yang Yang, Sai-Kit Yeung",
    venue: "IEEE Robotics and Automation Letters",
    year: 2026,
    status: "accepted",
    role: "first",
    roleLabel: "Co-first author",
    topic: "vision",
    summary: "Distills marine segmentation models through mask-guided feature separation and purification for lightweight deployment.",
    links: [
      {
        label: "Scholar",
        url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=pJzltu8AAAAJ&citation_for_view=pJzltu8AAAAJ:d1gkVwhDpl0C",
      },
      { label: "PDF", url: "https://saikit.org/static/projects/RAL26/MaskGuide_RAL2026.pdf" },
      { label: "Project page", url: "https://gintmr.github.io/MaskGuide/" },
    ],
  },
  {
    id: "imagetime",
    shortName: "ImageTime",
    title: "Can Image Models Imagine Time? ImageTime: A Novel Benchmark for Probing Visual World Modeling Through Spatiotemporal Consistency",
    authors: "Xinrui Wu, Lichen Huang",
    venue: "WACV 2027",
    year: 2026,
    status: "submitted",
    role: "first",
    roleLabel: "First author",
    topic: "vision",
    summary: "Evaluates visual world modeling in image models through the consistency of their spatial and temporal representations.",
    links: [
      { label: "arXiv", url: "https://arxiv.org/abs/2606.10620" },
      { label: "PDF", url: "https://www.alphaxiv.org/pdf/2606.10620" },
      { label: "Project page", url: "https://gintmr.github.io/ImagineTime/" },
      { label: "GitHub", url: "https://github.com/gintmr/ImagineTime" },
      { label: "Dataset", url: "https://huggingface.co/datasets/Xin-Rui/ImageTime_Benchmark" },
    ],
  },
  {
    id: "ocg",
    shortName: "OCG",
    title: "OCG: Optical Character Grounded Visual Reasoning with Flow Matching",
    authors: "Lichen Huang, Xinrui Wu",
    venue: "NeurIPS 2026 Workshop BeNTo",
    year: 2026,
    status: "submitted",
    role: "contributor",
    roleLabel: "Second author",
    topic: "vision",
    links: [{ label: "alphaXiv", url: "https://www.alphaxiv.org/abs/2608.ocg-optical-character-grounded-reasoning" }],
  },
  {
    id: "hiret",
    shortName: "HiReT",
    title: "HiReT: Hierarchical Relational Trajectory Modeling for Longitudinal Clinical Prognosis",
    authors: "Xinrui Wu, Wanqi Yang, Min Xu, Yutong Xie",
    venue: "ICLR 2027",
    year: 2026,
    status: "submitted",
    role: "first",
    roleLabel: "First author",
    topic: "clinical",
    summary: "Models hierarchical relationships within longitudinal clinical trajectories to support patient prognosis.",
    links: [],
  },
  {
    id: "clinical-world-models",
    shortName: "Clinical World Models",
    title: "Predicting the Future Is Not Enough: Toward Action-Aware Clinical World Models",
    authors: "Xinrui Wu, Wanqi Yang, Min Xu, Yutong Xie",
    venue: "ICLR 2027",
    year: 2026,
    status: "submitted",
    role: "first",
    roleLabel: "First author",
    topic: "clinical",
    summary: "Studies clinical world models that account for actions as well as future patient outcomes.",
    links: [],
  },
  {
    id: "parathinker",
    shortName: "ParaThinker",
    title: "ParaThinker: Native Parallel Reasoning for Scaling LLM Test-Time Compute",
    authors: "Hao Wen, Yifan Su, Feifei Zhang, Xinrui Wu, Yi Sun, Yunxin Liu, Yunhao Liu, Ya-Qin Zhang, Yuanchun Li",
    venue: "EMNLP 2026",
    year: 2026,
    status: "accepted",
    role: "contributor",
    roleLabel: "Contributing author",
    topic: "reasoning",
    summary: "Explores native parallel thinking as a way to scale language-model computation during inference.",
    links: [],
  },
  {
    id: "seatree",
    shortName: "SeaTree",
    title: "SeaTree: Tracing Marine Creatures through Taxonomic Tree",
    authors: "Yiwei Chen, Zheng Ziqiang, Xinrui Wu, Sai-Kit Yeung",
    venue: "AAAI 2027",
    year: 2026,
    status: "submitted",
    role: "contributor",
    roleLabel: "Contributing author",
    topic: "vision",
    summary: "Investigates marine-creature recognition using taxonomic tree structure.",
    links: [],
  },
];

export const experience = [
  {
    id: "mbzuai",
    organization: "Mohamed bin Zayed University of Artificial Intelligence",
    shortName: "MBZUAI",
    logo: "/assets/institutions/mbzuai.jpg",
    role: "Visiting Student",
    period: "Jan 2026 – Present",
    location: "Abu Dhabi, UAE",
    advisors: [
      { name: "Prof. Yutong Xie", url: "https://scholar.google.com/citations?user=ddDL9HMAAAAJ&hl" },
    ],
    description: "Developing structured clinical reasoning methods that integrate multi-stage patient information; studying longitudinal prognosis and training paradigms for clinical world models.",
    tags: ["Clinical AI", "World Models", "Longitudinal Prognosis"],
  },
  {
    id: "tsinghua-air",
    organization: "Tsinghua University, Institute for AI Industry Research",
    shortName: "Tsinghua AIR",
    logo: "/assets/institutions/tsinghua-air.png",
    role: "Research Intern",
    period: "Jan 2025 – Present",
    location: "Beijing, China",
    advisors: [
      { name: "Prof. Yuanchun Li", url: "https://yuanchun-li.github.io/" },
      { name: "Prof. Yunxin Liu", url: "https://scholar.google.com/citations?user=TFGBA9cAAAAJ&hl=zh-CN" },
    ],
    description: "Developed BudgetThinker for controllable chain-of-thought generation. Proportional control tokens and a two-stage training pipeline with reinforcement learning achieve over 95% budget adherence, with generalization to embodied spatial reasoning.",
    tags: ["LLM Reasoning", "Budget Control", "Reinforcement Learning"],
  },
  {
    id: "hkust",
    organization: "Hong Kong University of Science and Technology, VGD Group",
    shortName: "HKUST",
    logo: "/assets/institutions/hkust.png",
    role: "Research Intern",
    period: "Jul 2025 – Aug 2025",
    location: "Hong Kong",
    advisors: [
      { name: "Prof. Sai-Kit Yeung", url: "https://scholar.google.com/citations?user=16iMMwwAAAAJ&hl=zh-CN" },
    ],
    description: "Developed MaskGuide for lightweight marine segmentation through feature separation and purification. Tiny-MSAM achieves 99.4% of SAM's accuracy with 0.5% of its parameters at 164.7 FPS.",
    tags: ["Marine Vision", "Lightweight Segmentation", "Distillation"],
  },
  {
    id: "megvii",
    organization: "Megvii Technology Limited",
    shortName: "Megvii",
    logo: "/assets/institutions/megvii.png",
    role: "CV Algorithm Intern",
    period: "Feb 2025 – Jul 2025",
    location: "Beijing, China",
    advisors: [{ name: "Dr. Wei Ge" }],
    description: "Unified multimodal prompts as visual masks and built a data pipeline supporting billions of samples. Led the development and business deployment of an open-vocabulary detection model.",
    tags: ["Open-Vocabulary Detection", "Multimodal Prompts", "Deployment"],
  },
  {
    id: "uestc-cfm",
    organization: "UESTC, Center for Future Media",
    shortName: "UESTC CFM",
    logo: "/assets/institutions/uestc.png",
    role: "Research Intern",
    period: "Jun 2024 – Present",
    location: "Sichuan, China",
    advisors: [{ name: "Prof. Yang Yang", url: "https://cfm.uestc.edu.cn/~yangyang/" }],
    description: "Studying open-vocabulary object detection and segmentation, including false-positive reduction and recognition of objects with diverse visual appearances.",
    tags: ["Computer Vision", "Open-Vocabulary Perception", "Segmentation"],
  },
];

export const education = [
  {
    institution: "University of Electronic Science and Technology of China (UESTC)",
    logo: "/assets/institutions/uestc.png",
    degree: "B.S. in Software Engineering (Embedded System)",
    period: "Sep 2023 – Present",
    detail: "Sichuan, China · GPA: 3.63/4.0",
  },
];

export const awards = [
  {
    title: "UESTC Model Student Scholarship",
    detail: "Top 5% · Sci-Tech Innovation · October",
    year: 2025,
  },
  {
    title: "National Third Prize",
    detail: "China College Student Computer Design Competition · June",
    year: 2025,
  },
  {
    title: "National Third Prize",
    detail: "National College Student Innovation and Entrepreneurship Competition · May",
    year: 2025,
  },
  {
    title: "UESTC Model Student Scholarship",
    detail: "Top 5% · Sci-Tech Innovation · October",
    year: 2024,
  },
  {
    title: "National Second Prize",
    detail: "C4 National College Student Network Technology Challenge · August",
    year: 2024,
  },
  {
    title: "National Third Prize",
    detail: "C4 National College Student Network Technology Challenge · August",
    year: 2024,
  },
  {
    title: "Sichuan Provincial Second Prize",
    detail: "China College Student Computer Design Competition · June",
    year: 2024,
  },
];
